import { createClient } from 'jsr:@supabase/supabase-js@2';
const enc=new TextEncoder(), hex=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
const hash=async(s:string)=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))));
const token=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
const baseHeaders={'Content-Type':'application/json','Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};
const fail=(m:string,n=400)=>Object.assign(Error(m),{status:n});
Deno.serve(async req=>{const origin=req.headers.get('origin'),headers={...baseHeaders,...(origin==='https://mcdermottj639.github.io'?{'Access-Control-Allow-Origin':origin,Vary:'Origin'}:{})};const json=(x:unknown,n=200)=>new Response(JSON.stringify(x),{status:n,headers});try{
 if(origin&&origin!=='https://mcdermottj639.github.io')throw fail('Origin not allowed',403); if(req.method==='OPTIONS')return new Response(null,{status:204,headers});
 const path=new URL(req.url).pathname.replace(/^.*\/league-oracle(?=\/|$)/,'');
 const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
 const body=async()=>{const x=await req.json().catch(()=>{throw fail('Invalid JSON')});if(JSON.stringify(x).length>100000)throw fail('Request too large',413);return x};
 const session=async()=>{const t=(req.headers.get('authorization')||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(t))throw fail('Reopen your private Hurdstradamus link.',401);const {data}=await db.from('oracle_editor_sessions').select('*').eq('token_hash',await hash(t)).gt('expires_at',new Date().toISOString()).maybeSingle();if(!data)throw fail('Reopen your private Hurdstradamus link.',401);return data};
 if(path==='/health')return json({ok:true,storage:'supabase'});
 if(path==='/api/oracle/session'&&req.method==='POST'){const b=await body();if(typeof b.key!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(b.key))throw fail('Invalid editor link.',403);const {data:cap,error}=await db.from('oracle_capabilities').select('*').eq('capability_hash',await hash(b.key)).eq('active',true).maybeSingle();if(error)throw fail('Oracle storage is unavailable.',503);if(!cap)throw fail('Editor link is invalid or inactive.',403);const raw=token(),expires=new Date(Date.now()+365*864e5).toISOString(),{error:insertError}=await db.from('oracle_editor_sessions').insert({token_hash:await hash(raw),expires_at:expires,capability_id:cap.id});if(insertError)throw fail('Could not create editor session.',503);return json({token:raw,role:'oracle_editor',member:'Hurd',expires});}
 if(path==='/api/oracle/me'){await session();return json({role:'oracle_editor',member:'Hurd'});}
 if(path==='/api/oracle/state'){const editor=new URL(req.url).searchParams.get('editor')==='1';if(editor)await session();const {data,error}=await db.from('oracle_weeks').select('week,published_at,published,predictions,draft_predictions').order('week');if(error)throw fail('Oracle storage is unavailable.',503);const weeks=(data||[]).map((w:any)=>({week:w.week,published:w.published,publishedAt:w.published_at,predictions:editor?(w.draft_predictions||[]):(w.published?(w.predictions||[]):[])}));const current=weeks.find(w=>!w.published)?.week||weeks.at(-1)?.week||1;return json({year:2026,current,weeks});}
 if(['/api/oracle/save','/api/oracle/publish'].includes(path)&&req.method==='POST'){await session();const b:any=await body(),publish=path.endsWith('/publish');if(!Number.isInteger(b.week)||b.week<1||b.week>18||!Array.isArray(b.predictions)||b.predictions.length<1||b.predictions.length>8)throw fail('Add the scheduled matchups before saving.');for(const p of b.predictions){if(!p?.id||!p.matchup?.away?.id||!p.matchup?.home?.id||typeof p.winner!=='string'||typeof p.awayRecord!=='string'||typeof p.homeRecord!=='string'||typeof p.writeup!=='string'||p.writeup.length>10000||(p.confidence!==null&&!Number.isInteger(p.confidence))||(p.awayScore!==null&&!Number.isInteger(p.awayScore))||(p.homeScore!==null&&!Number.isInteger(p.homeScore)))throw fail('The draft contains an invalid matchup.');}if(publish&&(b.predictions.length!==6||b.predictions.some((p:any)=>!p.winner||!Number.isInteger(p.awayScore)||!Number.isInteger(p.homeScore)||p.awayScore<0||p.homeScore<0||!p.awayRecord.trim()||!p.homeRecord.trim()||!p.writeup.trim()||!Number.isInteger(p.confidence)||p.confidence<0||p.confidence>100)))throw fail('Complete all six predictions with valid scores, records, write-up, and confidence before publishing.');
 const ids=new Set<string>();for(const p of b.predictions){if(typeof p.id!=='string'||ids.has(p.id))throw fail('Each scheduled matchup must appear once.');ids.add(p.id);}const row={week:b.week,draft_predictions:b.predictions,updated_at:new Date().toISOString(),...(publish?{published:true,published_at:new Date().toISOString(),predictions:b.predictions}:{})};const {error}=await db.from('oracle_weeks').upsert(row,{onConflict:'week'});if(error)throw fail('Could not save the Oracle.',503);return json({ok:true,published:publish});}
 throw fail('Not found',404);
}catch(e){return new Response(JSON.stringify({error:(e as any).message||'The Oracle could not complete that request.'}),{status:(e as any).status||500,headers});}});
