/* Hurdstradamus — public prophecies and Hurd's separately-authorized editor. */
(() => {'use strict';
  const KEY='lh:oracle-session:v1', FILE='season/current.json';
  const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  let invite=null;
  try { const h=new URLSearchParams(location.hash.slice(1)); if(h.has('oracle-editor')){invite=h.get('oracle-editor');h.delete('oracle-editor');history.replaceState(null,'',location.pathname+location.search+(h.size?'#'+h:''));} }catch{}
  const S={config:null,data:null,season:null,session:read(KEY),week:null,editor:false,message:'',busy:false,host:null,crest:null,preview:null};
  let paintToken=0;
  const owns=token=>token===paintToken&&(!S.host?.dataset.view||S.host.dataset.view==='oracle');
  function read(k){try{return JSON.parse(localStorage.getItem(k)||'null');}catch{return null;}}
  const put=(k,v)=>{try{v?localStorage.setItem(k,JSON.stringify(v)):localStorage.removeItem(k);}catch{}};
  async function config(){if(S.config)return S.config;const r=await fetch('oracle-config.json',{cache:'no-store'});if(!r.ok)throw Error('Oracle configuration is unavailable.');const c=await r.json();if(!c.enabled||typeof c.api!=='string'||!c.api)return null;S.config=c;return c;}
  async function api(path,body,auth=false){const c=await config();if(!c)throw Error('Hurdstradamus is not live yet.');const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),15000);try{const r=await fetch(c.api+'/api/oracle/'+path,{method:body?'POST':'GET',cache:'no-store',signal:ctl.signal,headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{}),...(auth&&S.session?{Authorization:'Bearer '+S.session.token}:{})},...(body?{body:JSON.stringify(body)}:{})});const j=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401){S.editor=false;S.session=null;put(KEY,null);}throw Error(j.error||'The Oracle could not complete that request.');}return j;}finally{clearTimeout(timer);}}
  async function loadSeason(){if(S.season)return S.season;const r=await fetch(FILE,{cache:'no-store'});if(!r.ok)throw Error('The league schedule is unavailable.');const d=await r.json();if(!Array.isArray(d.t)||!d.t.length)throw Error('The league schedule is unavailable.');S.season=d;return d;}
  function matchupsFor(week){const t=S.season.t,at=week-1,seen=new Set(),out=[];for(const away of t){const home=t.find(x=>String(x.id)===String(away.sch?.[at]));if(!home)continue;const ids=[String(away.id),String(home.id)].sort(),id=`${week}:${ids.join('-')}`;if(seen.has(id))continue;seen.add(id);out.push({id,away:{id:String(away.id),name:String(away.n),record:`${away.w}-${away.l}`},home:{id:String(home.id),name:String(home.n),record:`${home.w}-${home.l}`}});}return out;}
  async function boot(){const c=await config();if(!c)return false;if(invite){const s=await api('session',{key:invite});S.session=s;put(KEY,s);invite=null;S.editor=true;window.dispatchEvent(new CustomEvent('oracle-editor-ready'));}else if(S.session){try{await api('me',null,true);S.editor=true;}catch{S.session=null;S.editor=false;put(KEY,null);}}return true;}
  function resultFor(p){const byId=Object.fromEntries((S.season?.t||[]).map(t=>[String(t.id),t]));const a=byId[p.matchup?.away?.id],h=byId[p.matchup?.home?.id],i=(p.week||S.week)-1;if(!a||!h||!Number.isFinite(a.s?.[i])||!Number.isFinite(h.s?.[i])||a.s[i]<=0||h.s[i]<=0||a.s[i]===h.s[i])return null;const actual=a.s[i]>h.s[i]?a.n:h.n;return p.winner===actual?'right':'wrong';}
  function records(w){const all=(S.data?.weeks||[]).filter(x=>x.published).flatMap(x=>(x.predictions||[]).map(p=>({...p,week:x.week})));const count=a=>a.reduce((o,p)=>{const r=resultFor(p);if(r)o[r]++;return o;},{right:0,wrong:0});return {week:count((w?.predictions||[]).map(p=>({...p,week:w.week}))),all:count(all)};}
  const logo=(m,size)=>S.crest?S.crest(m,size):'';
  function teamHTML(t){const manager=window.LeagueESPN?.mgrFor?.(t.name,[])||'';return `<div class="or-team">${manager?logo(manager,34):''}<span>${esc(t.name)}<small>${esc(t.record||'')}</small></span></div>`;}
  function publicHTML(w,preview=false){if(!w?.published&&!preview)return `<section class="or-empty"><b>The next Hurdstradamus is waiting to be published.</b><p>Hurd’s prophecies will appear here for everyone once he releases the week.</p></section>`;const r=records(w),notice=preview?'<p class="or-status"><b>Private preview</b> · Only Hurd can see this draft. <button data-or="edit">Back to editor</button></p>':'';return `${notice}<section class="or-head"><p class="or-kicker">Week ${w.week} · Hurdstradamus</p><h2>The Commish Has Spoken</h2><p>${preview?'Draft preview — not published':`Published ${esc(new Date(w.publishedAt).toLocaleString())}`}</p><div class="or-head-stats"><b>${r.week.right}–${r.week.wrong}<small>This week</small></b><b>${r.all.right}–${r.all.wrong}<small>All-time</small></b></div></section>${w.predictions.map((p,i)=>`<article class="or-card"><div class="or-card-kicker">🔮 The Prophecy · Game ${i+1}${p.upset?'<b class="or-upset">Upset Watch</b>':''}</div><div class="or-versus">${teamHTML(p.matchup.away)}<strong>${p.awayScore??'—'} <i>—</i> ${p.homeScore??'—'}</strong>${teamHTML(p.matchup.home)}</div><div class="or-call"><span>Hurd’s pick</span><b>${esc(p.winner||'Not selected')}</b></div><p>${esc(p.writeup||'No write-up yet.')}</p><footer><b>${p.confidence??'—'}% confidence</b><span>Projected records: ${esc(p.awayRecord||'—')} / ${esc(p.homeRecord||'—')}</span></footer></article>`).join('')}`;}
  function editorHTML(w){const all=matchupsFor(S.week),draft=Object.fromEntries((w?.predictions||[]).map(p=>[p.id,p])),complete=all.filter(m=>completePrediction(draft[m.id])).length;return `<section class="or-head"><p class="or-kicker">Commissioner mode · Week ${S.week}</p><h2>Craft the Prophecy</h2><p>${complete} of ${all.length} complete · drafts are private until published.</p><div class="or-progress"><i style="width:${all.length?complete/all.length*100:0}%"></i></div></section><p class="or-status" role="status">${esc(S.message)}</p>${all.map((m,i)=>{const p={matchup:m,...draft[m.id]};return `<article class="or-edit" data-or-id="${esc(m.id)}"><p class="or-edit-kicker">Matchup ${i+1} of ${all.length}</p><div class="or-edit-teams">${teamHTML(m.away)}<label>Projected score<input data-f="awayScore" type="number" min="0" max="300" value="${esc(p.awayScore??'')}"></label>${teamHTML(m.home)}<label>Projected score<input data-f="homeScore" type="number" min="0" max="300" value="${esc(p.homeScore??'')}"></label></div><div class="or-fields"><label>${esc(m.away.name)} record<input data-f="awayRecord" maxlength="8" value="${esc(p.awayRecord??m.away.record)}"></label><label>${esc(m.home.name)} record<input data-f="homeRecord" maxlength="8" value="${esc(p.homeRecord??m.home.record)}"></label></div><fieldset><legend>Predicted winner</legend>${[m.away.name,m.home.name].map(n=>`<label class="or-winner"><input data-f="winner" type="radio" name="${esc(m.id)}" value="${esc(n)}" ${p.winner===n?'checked':''}> ${esc(n)}</label>`).join('')}</fieldset><label>Hurd’s write-up<textarea data-f="writeup" maxlength="500" placeholder="The crystal ball sees…">${esc(p.writeup??'')}</textarea><small data-count>0 / 500</small></label><div class="or-fields"><label>Confidence<input data-f="confidence" type="number" min="0" max="100" value="${esc(p.confidence??'')}">%</label><label class="or-check"><input data-f="upset" type="checkbox" ${p.upset?'checked':''}> Upset Watch</label></div></article>`;}).join('')}<div class="or-actions"><button data-or="preview" ${S.busy?'disabled':''}>Preview</button><button data-or="save" ${S.busy?'disabled':''}>${S.busy?'Saving…':'Save draft'}</button><button data-or="publish" ${S.busy||complete!==all.length?'disabled':''}>Publish Week ${S.week}</button></div>${complete!==all.length?`<p class="or-lock">${all.length-complete} matchup${all.length-complete===1?'':'es'} still need a winner, both scores, records, write-up, and confidence before publishing.</p>`:''}`;}
  function completePrediction(p){return !!(p&&p.winner&&Number.isInteger(Number(p.awayScore))&&Number(p.awayScore)>=0&&Number.isInteger(Number(p.homeScore))&&Number(p.homeScore)>=0&&p.awayRecord?.trim()&&p.homeRecord?.trim()&&p.writeup?.trim()&&Number.isInteger(Number(p.confidence))&&Number(p.confidence)>=0&&Number(p.confidence)<=100);}
  function readEditor(){return [...S.host.querySelectorAll('[data-or-id]')].map(el=>{const m=matchupsFor(S.week).find(x=>x.id===el.dataset.orId),v=f=>el.querySelector(`[data-f="${f}"]`)?.value.trim()||'',n=f=>{const x=v(f);return x===''?null:Number(x);},winner=el.querySelector('[data-f="winner"]:checked')?.value||'';return {id:m.id,matchup:m,winner,awayScore:n('awayScore'),homeScore:n('homeScore'),awayRecord:v('awayRecord'),homeRecord:v('homeRecord'),writeup:v('writeup'),confidence:n('confidence'),upset:el.querySelector('[data-f="upset"]').checked};});}
  function syncEditorControls(){if(!S.editor||!S.host)return;const total=matchupsFor(S.week).length,complete=readEditor().filter(completePrediction).length,publish=S.host.querySelector('[data-or="publish"]'),lock=S.host.querySelector('.or-lock'),bar=S.host.querySelector('.or-progress i'),head=S.host.querySelector('.or-head>p:not(.or-kicker)');if(publish)publish.disabled=S.busy||complete!==total;if(lock)lock.textContent=`${total-complete} matchup${total-complete===1?'':'es'} still need a winner, both scores, records, write-up, and confidence before publishing.`;if(bar)bar.style.width=(total?complete/total*100:0)+'%';if(head)head.textContent=`${complete} of ${total} complete · drafts are private until published.`;}
  async function render(token){await loadSeason();if(!owns(token))return false;S.data=await api('state'+(S.editor?'?editor=1':''),null,S.editor);if(!owns(token))return false;S.week=S.week||S.data.current||1;const saved=S.data.weeks.find(x=>x.week===S.week)||{week:S.week,predictions:[]},w=S.preview?{...saved,published:true,predictions:S.preview}:saved;S.host.innerHTML=`<div class="oracle"><nav class="or-nav"><label>Week <select data-or-week>${S.data.weeks.map(x=>`<option value="${x.week}" ${x.week===S.week?'selected':''}>${x.week}</option>`).join('')}</select></label>${S.editor?'<b>Hurd editor</b>':''}</nav>${S.preview?publicHTML(w,true):(S.editor?editorHTML(w):publicHTML(w))}</div>`;S.host.querySelectorAll('textarea[data-f="writeup"]').forEach(t=>{const c=t.parentElement.querySelector('[data-count]'),sync=()=>c.textContent=`${t.value.length} / 500`;t.addEventListener('input',sync);sync();});if(S.editor&&!S.preview)S.host.querySelectorAll('[data-or-id] input,[data-or-id] textarea').forEach(el=>{el.addEventListener('input',syncEditorControls);el.addEventListener('change',syncEditorControls);});return true;}
  async function paint(host,crest){const token=++paintToken;try{S.host=host;S.crest=crest;S.preview=null;host.innerHTML='<div class="oracle"><section class="or-empty"><b>Opening Hurdstradamus…</b><p>Loading this week’s prophecies.</p></section></div>';if(!await boot()||!owns(token))return;if(!await render(token)||!owns(token))return;host.onclick=async e=>{const b=e.target.closest('[data-or]');if(!b)return;const action=b.dataset.or;if(action==='preview'){S.preview=readEditor();await render(token);return;}if(action==='edit'){S.preview=null;await render(token);return;}S.busy=true;S.message='';try{const predictions=readEditor();await api(action,{week:S.week,predictions},true);S.message=action==='publish'?'Week published to the league.':'Private draft saved.';}catch(err){S.message=err.message;}finally{S.busy=false;await render(token);}};host.onchange=e=>{if(e.target.matches('[data-or-week]')){S.week=Number(e.target.value);S.preview=null;render(token).catch(err=>{S.message=err.message;});}};}catch(e){if(owns(token))host.innerHTML=`<section class="or-empty"><b>The Oracle cannot open right now.</b><p>${esc(e.message)}</p></section>`;}}
  window.LeagueOracle={paint,get entry(){return !!invite;},get available(){return true;}};
})();
