/* Parlay v2 is launch-gated. No writes to legacy Firebase; the legacy reader remains intact. */
(function(){
 'use strict';
 const legacy=window.LeagueParlay,LH=window.LeagueHistory,KEY='lh:parlay-session:v2',CACHE='lh:parlay-state:v2',ACTIVE='lh:parlay-enabled:v2';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null');}catch{return null;}},write=(k,v)=>{try{v?localStorage.setItem(k,JSON.stringify(v)):localStorage.removeItem(k);}catch{}};
 let invite=null,configRequest=null,paintId=0,sharedPick=null;try{const m=/(?:^#|&)parlay-organizer=([A-Za-z0-9_-]{43})(?:&|$)/.exec(location.hash);if(m){invite=m[1];history.replaceState(null,'',location.pathname+location.search);}}catch{}
 const S={host:null,cr:null,config:null,data:null,tab:'picks',week:null,manage:false,target:'',draft:null,editing:false,busy:false,message:'',error:false,session:read(KEY),pending:false,authTried:false,verified:false,configError:false,refreshing:false,checking:false};
 window.ParlayNext={entry:!!invite};
 const money=n=>n==null?'—':n.toLocaleString(undefined,{style:'currency',currency:'USD'}),sign=n=>n==null?'—':(n>0?'+':'')+n.toLocaleString();
 const name=m=>LH?.name(m)||m,me=()=>LH?.me(),owns=()=>S.host?.dataset.view==='parlay'&&S.host?.dataset.parlayMode==='next',admin=()=>S.verified&&S.session?.role==='organizer',week=()=>S.data?.weeks.find(w=>w.week===S.week),member=()=>S.manage&&admin()?S.target:me();
 const age=t=>{if(!t)return 'No update yet';const n=Math.max(0,Math.floor((Date.now()-t)/1000));return n<60?`${n}s ago`:n<3600?`${Math.floor(n/60)}m ago`:`${Math.floor(n/3600)}h ago`;};
 const kickoff=t=>new Date(t).toLocaleString(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'});
 const badge=(s)=>`<span class="pn-badge pn-${s}">${({upcoming:'Upcoming',live:'Live',hit:'Hit',miss:'Miss',push:'Push',pending:'Pending review'})[s]||esc(s)}</span>`;
 async function config(){
  if(S.config)return S.config;
  if(!configRequest)configRequest=(async()=>{
   try{const r=await fetch('parlay/config.json',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error();const c=await r.json();if(typeof c.enabled!=='boolean'||(c.enabled&&(typeof c.api!=='string'||!Number.isInteger(c.year))))throw Error();
    if(c.enabled){write(ACTIVE,c);S.config=c;}
    else if(read(ACTIVE)?.enabled)throw Error('The upgraded parlay is temporarily unavailable.');
    else S.config=c;
    S.configError=false;return S.config;
   }catch{S.configError=true;const saved=read(ACTIVE);if(saved?.enabled){S.config=saved;return saved;}throw Error('Could not check the parlay connection. Try again when connected.');}
   finally{configRequest=null;}
  })();return configRequest;
 }
 async function api(path,body,authenticated=false,token=S.session?.token){
  const base=S.config.api||'',r=await fetch(base+'/api/parlay/'+path,{method:body?'POST':'GET',cache:'no-store',signal:AbortSignal.timeout(15000),headers:{...(body?{'Content-Type':'application/json'}:{}),...(authenticated&&token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});
  let j;try{j=await r.json();}catch{throw Error('The parlay service is unavailable.');}if(!r.ok){if(r.status===401){S.session=null;S.verified=false;write(KEY,null);S.manage=false;}throw Object.assign(Error(j.error||'Could not complete that request.'),{status:r.status});}return j;
 }
 function say(message,error=false){S.message=message;S.error=error;}
 async function restore(){
  if(S.session?.api!==undefined&&(S.session.api!==S.config.api||S.session.year!==S.config.year)){S.session=null;S.verified=false;write(KEY,null);}
  if(invite){const key=invite;try{S.session={...await api('session',{key}),api:S.config.api,year:S.config.year};invite=null;S.verified=true;write(KEY,S.session);S.authTried=true;window.dispatchEvent(new CustomEvent('parlay-organizer-ready'));S.manage=true;S.target='Zach';say('Organizer access is ready on this device.');}catch(e){S.verified=false;say(e.message,true);}}
  else if(S.session&&!S.authTried){try{const auth=await api('me',null,true);S.session={...S.session,...auth,api:S.config.api,year:S.config.year};S.verified=true;S.authTried=true;write(KEY,S.session);if(admin()&&!me())window.dispatchEvent(new CustomEvent('parlay-organizer-ready'));}catch(e){S.verified=false;say(e.message,true);}}
 }
 async function memberSession(m){if(admin())return S.session;if(!m)throw Error('Choose your name at the top of the app first.');if(!S.session||!S.verified||S.session.member!==m){S.session={...await api('session',{member:m}),api:S.config.api,year:S.config.year};S.verified=true;write(KEY,S.session);}return S.session;}
 async function refresh(force=false){if(S.refreshing)return;S.refreshing=true;try{const data=await api('state');if(data.year!==S.config.year||!Array.isArray(data.weeks)||!Array.isArray(data.roster))throw Error('Invalid parlay state');S.data=data;if(!data.weeks.some(w=>w.week===S.week))S.week=data.current;write(CACHE,{api:S.config.api,at:Date.now(),data});S.pending=S.configError||data.writable===false;if(force)say(S.pending?'The parlay is temporarily read-only.':'Updated just now.');}catch(e){S.pending=true;if(force||!S.data)say('Could not refresh. Showing the last saved data; editing is unavailable.',true);}finally{S.refreshing=false;S.checking=false;if(owns()&&!S.busy&&!S.host.querySelector('input:focus,textarea:focus,select:focus'))render();}}
 const pickFor=m=>week()?.ticket.legs.find(p=>p.member===m);
 const available=g=>g.state==='pre'&&Date.now()<g.kick&&!week().ticket.legs.some(p=>p.member!==member()&&p.gameId===g.id);
 function gameHTML(g){
  const cols=[['Spread','spread',[g.away,g.home]],['Total','total',['over','under']],['Moneyline','ml',[g.away,g.home]]];
  return `<article class="pn-game"><div class="pn-row"><b>${esc(g.away)} at ${esc(g.home)}</b><small>${esc(kickoff(g.kick))}</small></div><div class="pn-markets">${cols.map(([title,market,sides])=>`<div><small>${title}</small>${sides.map(side=>{const q=g.markets.find(q=>q.market===market&&q.side===side),on=S.draft?.gameId===g.id&&S.draft?.market===market&&S.draft?.side===side;return `<button type="button" data-pn="select" data-game="${esc(g.id)}" data-market="${market}" data-side="${side}" aria-pressed="${!!on}" ${!q||S.pending||week().ticket.locked?'disabled':''} aria-label="${esc(q?.label||side+' unavailable')}"><b>${market==='total'?`${side==='over'?'Over':'Under'} ${q?.line??'—'}`:market==='spread'?`${esc(side)} ${sign(q?.line)}`:esc(side)}</b><span>${sign(q?.odds)}</span></button>`;}).join('')}</div>`).join('')}</div></article>`;
 }
 function rowHTML(p){
  const g=p.game,stale=g&&Date.now()-g.seenAt>90000;
  const warnings=[p.staleQuote?'Last available pregame quote':'',p.missingQuote?'Kickoff quote unavailable':'',stale&&p.result==='live'?'Score update delayed':''].filter(Boolean);
  if(p.staleQuote&&p.quote?.observedAt)warnings.push('Quote observed '+age(p.quote.observedAt));
  return `<div class="pn-leg"><div class="pn-row"><div class="pn-member">${S.cr?S.cr(p.member,28):''}<b>${esc(name(p.member))}</b>${p.member===me()?'<span class="lg-you">YOU</span>':''}</div>${badge(p.result)}</div><p><b>${esc(p.quote?.label||p.original?.label||p.description)} · ${sign(p.quote?.odds)}</b></p>${g&&['in','post'].includes(g.state)&&Number.isFinite(g.awayScore)&&Number.isFinite(g.homeScore)?`<p>${esc(g.away)} ${g.awayScore} — ${esc(g.home)} ${g.homeScore} <small>${esc(g.detail)}</small></p>`:`<small class="pn-block">${g?esc(kickoff(g.kick)):'Matchup needs review'}${p.lockedAt?' · Locked at kickoff':''}</small>`}${p.result==='live'?`<p class="pn-position">${esc(p.progress)}</p>`:''}${warnings.length?`<small class="pn-block">${esc(warnings.join(' · '))}</small>`:''}${p.addedBy==='organizer'?'<small class="pn-block">Added by organizer</small>':''}${p.reviewNote?`<small class="pn-block">Reviewed: ${esc(p.reviewNote)}</small>`:''}${admin()&&!S.pending&&(p.result==='pending'||p.manualResult)&&p.lockedAt&&p.game?.state!=='in'?`<details class="pn-review" data-detail="review-${esc(p.member)}"><summary>Review result</summary><label>Outcome<select data-review="${esc(p.member)}"><option value="pending">Pending</option><option value="hit">Hit</option><option value="miss">Miss</option><option value="push">Push / void</option></select></label><label>Reason<input maxlength="300" data-note="${esc(p.member)}" placeholder="Verified result or void reason"></label><button data-pn="review" data-member="${esc(p.member)}">Save result</button></details>`:''}</div>`;
 }
 function picksHTML(w){
  const p=pickFor(member()),unmapped=w.unmapped.find(x=>x.member===member()),closed=S.week!==S.data.current||p?.lockedAt||w.ticket.locked,canPick=member()&&!closed;
  let out=`<div class="pn-row"><h2 class="pn-title">${p?'Your pick is in':'Choose your pick'}</h2><b>${w.ticket.legs.length} of 12 picks in</b></div>`;
  if(S.manage&&admin())out+=`<section class="pn-card"><div class="pn-row"><b>Manage picks</b><button data-pn="manage">Close</button></div><label>Pick for<select id="pn-target">${S.data.roster.map(m=>`<option value="${m}" ${m===S.target?'selected':''}>${esc(name(m))}${pickFor(m)?' · pick saved':''}</option>`).join('')}</select></label><small>Uses this member’s pick slot and record.</small></section>`;
  if(p)out+=`<section class="pn-card pn-saved"><div><b>${esc(p.quote?.label)} · ${sign(p.quote?.odds)}</b><small class="pn-block">${p.lockedAt?'Locked at kickoff':'Saved · updates until kickoff'}${S.manage?' · '+esc(name(member())):''}</small></div><div class="pn-actions"><button data-pn="edit" ${closed?'disabled':''}>${S.editing?'Done':'Change'}</button><button data-pn="clear" ${closed||S.pending?'disabled':''}>Clear</button></div></section>`;
  if(unmapped)out+=`<div class="pn-card"><b>Existing pick needs a matchup</b><p>${esc(unmapped.original?.label)}</p><small>Select its game below to keep tracking it. The original entry has been retained.</small></div>`;
  if(!member())out+='<p class="pn-note">Choose your name in the app header to save a pick. You can still view the shared ticket.</p>';
  if(w.ticket.locked)out+='<p class="pn-note"><b>This parlay is locked.</b> A game has started, so the ticket cannot be changed.</p>';
  if(!p||S.editing){const games=w.games.filter(g=>available(g));out+=`<p class="pn-note">DraftKings via ESPN · Updated ${esc(age(w.updatedAt))}${w.feedError?' · Feed delayed':''}</p>`;
   out+=games.length?games.map(gameHTML).join(''):'<div class="pn-card">No available games with open kickoffs. Check back for the next board.</div>';
   if(canPick&&S.draft&&S.draft.market!=='prop'){const g=w.games.find(g=>g.id===S.draft.gameId),q=g&&available(g)&&g.markets.find(q=>q.market===S.draft.market&&q.side===S.draft.side);out+=`<div class="pn-card pn-saved pn-draft"><b>${esc(q?.label||'Selection unavailable')} · ${sign(q?.odds)}</b><button class="pn-primary" data-pn="save" ${!q||S.pending||S.busy?'disabled':''}>${S.busy?'Saving…':S.manage?'Save for '+esc(name(member())):'Save my pick'}</button></div>`;}
   if(canPick)out+=`<details class="pn-card" data-detail="prop"><summary>Other bet / player prop</summary><label>Matchup<select id="pn-prop-game"><option value="">Choose a game</option>${games.map(g=>`<option value="${esc(g.id)}">${esc(g.away)} at ${esc(g.home)}</option>`).join('')}</select></label><label>Pick<input id="pn-prop" maxlength="120" placeholder="Player and exact bet"></label><label>Odds<input id="pn-prop-odds" inputmode="decimal" placeholder="−110"></label><small>Write-in lines do not auto-update. Unsupported results need organizer review.</small><button data-pn="prop" ${S.pending?'disabled':''}>Save prop${S.manage?' for '+esc(name(member())):''}</button></details>`;
   out+='<p class="pn-note">Games picked by others are off the board. One game per member.</p>';
  }
  out+=`<section class="pn-card pn-members"><details data-detail="who"><summary>Who is in · ${w.ticket.legs.length} members</summary><p class="pn-note">Updated ${esc(age(w.updatedAt))}${w.feedError?' · Feed delayed':''} · Lines update until kickoff.</p>${w.ticket.legs.map(rowHTML).join('')||'<p>Nobody has submitted yet.</p>'}</details><details data-detail="missing"><summary>Still to pick · ${12-w.ticket.legs.length} members</summary><p>${S.data.roster.filter(m=>!pickFor(m)).map(m=>esc(name(m))).join(' · ')||'Everyone is in.'}</p></details></section>`;return out;
 }
 function payerHTML(w){const p=w.payer;return `<div class="pn-payer"><small>THIS WEEK’S $10</small><p>${p?.status==='ready'?`<b>${p.members[0]==='Zach'?'Zach covers this week’s $10':esc(name(p.members[0]))+' owes Zach $10'}</b> · Week ${p.previousWeek} low: ${p.score}`:p?.status==='tie'?`Tied low score: ${p.members.map(m=>esc(name(m))).join(' / ')} · payer to be decided`:w.week===1?'Week 1 · reimbursement to be decided. No prior week’s score.':'Awaiting the prior week’s final fantasy scores.'}</p></div>`;}
 function placedOddsHTML(w){const p=w.placedTicket;
  return `<section class="pn-placed"><div class="pn-row"><b>Placed ticket · DraftKings</b>${p?`<strong>${sign(p.odds)}</strong>`:''}</div>${p?`<p>$${p.stake} stake · <b>${money(p.potentialReturn)} potential return</b></p><small>${money(p.potentialProfit)} potential profit · Odds entered by organizer. Return includes stake, before any pushes or voids.</small>`:'<p class="pn-note">Actual ticket odds haven’t been entered yet.</p>'}${admin()?`<details data-detail="placed-odds"><summary>${p?'Edit actual odds':'Add actual odds'}</summary><label>Combined American odds<input id="pn-placed-odds" type="text" maxlength="24" placeholder="e.g. +12500" value="${p?.odds??''}" ${S.pending?'disabled':''}></label><div class="pn-actions"><button data-pn="placed-odds" class="pn-primary" ${S.pending?'disabled':''}>Save actual odds</button>${p?`<button data-pn="clear-placed-odds" ${S.pending?'disabled':''}>Clear</button>`:''}</div></details>`:''}</section>`;
 }
 function ticketHTML(w){const t=w.ticket,heading=({lost:'Ticket lost.',won:'Every leg hit.',refunded:'Ticket refunded.',collecting:'The ticket is taking shape.',incomplete:'Incomplete ticket.',empty:'Waiting for picks.',live:'Still alive.'})[t.status];
  const group=(key,title,collapse=false)=>{const legs=t.legs.filter(l=>key.includes(l.result));if(!legs.length)return '';return collapse?`<details class="pn-card" data-detail="completed"><summary>${title} · ${legs.length} legs</summary>${legs.map(rowHTML).join('')}</details>`:`<section class="pn-card"><h3>${title} · ${legs.length}</h3>${legs.map(rowHTML).join('')}</section>`;};
  const reset=admin()&&S.week===S.data.current&&t.resetEligible?`<section class="pn-card"><b>Thursday reset available</b><p class="pn-note">A Thursday leg lost. Reset opens a fresh ticket and clears this week’s current picks and actual ticket odds. The lost attempt stays in Season tracking.</p><button data-pn="reset-parlay" ${S.pending||S.busy?'disabled':''}>Reset this parlay</button></section>`:'';
  const prior=w.priorTickets?.length?`<section class="pn-card"><h3>Earlier Week ${w.week} attempt${w.priorTickets.length>1?'s':''}</h3>${w.priorTickets.map((x,i)=>`<p><b>Attempt ${i+1} · ${x.ticket.hit}/${x.ticket.legs.length} hit · ${esc(x.ticket.status)}</b><small class="pn-block">Reset after a Thursday miss · retained in Season tracking</small></p>`).join('')}</section>`:'';
  return `<h2 class="pn-title">${heading}</h2><p class="pn-note">Updated ${esc(age(w.updatedAt))}${w.feedError?' · Feed delayed':''} · ${t.locked?'Ticket locked after first kickoff.':'Lines update until kickoff.'}</p><section class="pn-card pn-ticket-summary"><b>${t.legs.length}-leg ${t.full?'parlay':'partial ticket'}</b><div class="pn-stats"><div><strong>${sign(t.combinedOdds)}</strong><small>Tracked odds</small></div><div><strong>$10</strong><small>Weekly stake</small></div><div><strong>${money(t.returned??t.estimatedReturn)}</strong><small>${t.returned!==null?'Tracked return':'Est. return'}</small></div></div><p class="pn-note">${t.status==='lost'?'Tracked net: −$10':t.estimatedReturn!==null?money(t.estimatedReturn-10)+' estimated profit':'Waiting for complete prices'}</p><div class="pn-progress" aria-label="${t.hit} hit, ${t.miss} missed, ${t.push} pushed">${t.legs.map(l=>`<span class="pn-${l.result}"></span>`).join('')}</div><p class="pn-note">${t.hit} hit · ${t.legs.filter(l=>l.result==='live').length} live · ${t.legs.filter(l=>l.result==='upcoming').length} upcoming${t.miss?' · '+t.miss+' missed':''}${t.push?' · '+t.push+' pushed':''}${t.legs.some(l=>l.result==='pending')?' · results pending':''}</p>${payerHTML(w)}${placedOddsHTML(w)}</section>${prior}${reset}${group(['live'],'Live')}${group(['upcoming'],'Upcoming')}${group(['pending'],'Pending review')}${group(['hit','miss','push'],'Completed',true)}<p class="pn-note">Tracked using kickoff lines; actual ticket may differ.</p>`;
 }
 function seasonHTML(){
  const weeks=S.data.weeks.filter(w=>w.ticket.legs.length||(w.priorTickets||[]).length),tickets=weeks.flatMap(w=>[...(w.priorTickets||[]).map(x=>({...x.ticket,week:w.week,attempt:true})),...(w.ticket.legs.length?[{...w.ticket,week:w.week,attempt:false}]:[])]),settled=tickets.filter(t=>t.settled&&t.full),counted=settled.filter(t=>t.returned!==null),hit=tickets.reduce((n,t)=>n+t.hit,0),decided=tickets.reduce((n,t)=>n+t.hit+t.miss,0),net=counted.reduce((n,t)=>n+t.net,0);
  const records=S.data.roster.map(m=>{const legs=tickets.flatMap(t=>t.legs).filter(l=>l.member===m),win=legs.filter(l=>l.result==='hit').length,loss=legs.filter(l=>l.result==='miss').length,push=legs.filter(l=>l.result==='push').length;return {m,win,loss,push,n:win+loss,rate:win+loss?win/(win+loss):null};}).sort((a,b)=>(b.rate??-1)-(a.rate??-1)||b.win-a.win||a.m.localeCompare(b.m));
  const best=settled.filter(t=>t.miss).sort((a,b)=>b.hit-a.hit)[0];
  return `<h2 class="pn-title">${S.data.year} · The season’s story</h2>${!tickets.length?'<div class="pn-card">Your season record starts after the first ticket settles.</div>':`<section class="pn-card pn-stats"><div><strong>${tickets.length}</strong><small>Tickets tracked</small></div><div><strong>${settled.filter(t=>t.status==='won').length}</strong><small>Tracked wins</small></div><div><strong>${hit}/${decided}</strong><small>Decided legs hit</small></div><div><strong>${money(counted.length*10)}</strong><small>Settled full stakes</small></div><div><strong>${money(counted.reduce((n,t)=>n+t.returned,0))}</strong><small>Tracked return</small></div><div><strong>${money(net)}</strong><small>Tracked net</small></div></section>`}<section class="pn-card"><h3>Who carries the ticket</h3><p class="pn-note">${records.some(r=>r.n||r.push)?'Record · hit rate. A dash means no settled picks.':'No picks settled yet. Records appear as games finish.'}</p>${records.map(r=>`<div class="pn-row pn-record"><b>${esc(name(r.m))}</b><span>${r.n||r.push?`${r.win}–${r.loss}${r.push?'–'+r.push:''} · ${r.rate===null?'—':Math.round(r.rate*100)+'%'}<small class="pn-block">${r.n} decided${r.push?' · '+r.push+' pushes':''}</small>`:'<span aria-label="No settled picks">—</span>'}</span></div>`).join('')}</section><section class="pn-card"><h3>Past tickets</h3>${tickets.map(t=>`<button class="pn-history" data-pn="history" data-week="${t.week}"><b>Week ${t.week}${t.attempt?' · reset attempt':''}</b><span>${t.hit}/${t.legs.length} hit · ${esc(t.status)} ›</span></button>`).join('')||'<p>No tickets yet.</p>'}</section>${best?`<div class="pn-card">Closest call · Week ${best.week} · ${best.hit} hits, ${best.miss} misses</div>`:''}`;
 }
 function render(){if(!owns())return;const open=[...S.host.querySelectorAll('details[open][data-detail]')].map(e=>e.dataset.detail),y=window.scrollY;
  if(!S.data){S.host.innerHTML=`<div class="ffp-card">${esc(S.message||'Loading the shared parlay…')} <button data-pn="retry">Retry</button></div>`;return;}
  const w=week();if(!w)return;
  S.host.innerHTML=`<div class="pn">${sharedPick?`<div class="pn-card"><b>Shared pick · Week ${esc(sharedPick.k)}</b><p>${esc(name(sharedPick.m))}: ${esc(sharedPick.p)} · ${sign(Number(sharedPick.o))}</p><small>Original shared entry. The current shared ticket below is authoritative.</small></div>`:''}<nav class="pn-tabs" aria-label="Parlay tabs">${['picks','ticket','season'].map(t=>`<button data-pn="tab" data-tab="${t}" aria-pressed="${S.tab===t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</nav>${S.data.preview?'<p class="pn-note">Isolated preview · sample data · no live league writes</p><label>Preview scenario<select id="pn-demo"><option value="">Choose a scenario</option><option value="before">Before kickoff</option><option value="live">Games live</option><option value="lost">Final · one leg missed</option><option value="won">Final · all hit</option></select></label>':''}<div class="pn-row pn-toolbar"><label class="pn-week">${S.tab==='season'?'Season '+S.data.year:`<select id="pn-week" aria-label="Parlay week">${S.data.weeks.map(x=>`<option value="${x.week}" ${x.week===S.week?'selected':''}>Week ${x.week}</option>`).join('')}</select>`}</label><div class="pn-actions">${admin()?'<button data-pn="manage">Manage picks</button>':''}<button data-pn="refresh" aria-label="Refresh parlay">Refresh</button></div></div><p role="status" aria-live="polite" class="pn-message ${S.error?'pn-error':''}">${esc(S.message)}</p>${S.pending&&S.checking&&!S.configError?'<p class="pn-note" role="status">Checking for updates · showing saved picks.</p>':S.pending?'<p class="pn-error">Parlay is read-only. Your saved picks remain visible; reconnect or wait for setup to finish.</p>':''}${S.tab==='picks'?picksHTML(w):S.tab==='ticket'?ticketHTML(w):seasonHTML()}</div>`;
  open.forEach(id=>{const d=[...S.host.querySelectorAll('[data-detail]')].find(e=>e.dataset.detail===id);if(d)d.open=true;});window.scrollTo(0,y);
 }
 async function save(input){
  if(S.busy||S.pending)return;
  const m=member(),p=pickFor(m),selectedWeek=S.week,year=S.data.year,request={year,week:selectedWeek,member:m,revision:week()?.revisions?.[m]??p?.revision??0,...input};S.busy=true;
  try{const actor=await memberSession(m);await api('pick',request,true,actor.token);if(member()===m&&S.week===selectedWeek){S.draft=null;S.editing=false;say(input.clear?'Pick cleared.':'Saved — the league can see it.');}await refresh();}
  catch(e){say(e.message,true);await refresh();}finally{S.busy=false;render();}
 }
 document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-pn]');if(!b||!owns()||b.disabled||S.busy)return;const act=b.dataset.pn;
  if(act==='tab'){S.tab=b.dataset.tab;S.draft=null;S.editing=false;S.manage=false;say('');render();}
  if(act==='manage'&&admin()){S.manage=!S.manage;S.target=S.target||me()||'Zach';S.tab='picks';S.draft=null;S.editing=false;render();}
  if(act==='edit'){S.editing=!S.editing;S.draft=null;render();}
  if(act==='select'){S.draft={gameId:b.dataset.game,market:b.dataset.market,side:b.dataset.side};say('');render();}
  if(act==='save'&&S.draft)await save(S.draft);
  if(act==='clear')await save({clear:true});
  if(act==='reset-parlay'&&admin()&&!S.pending){
   if(!confirm('Reset this parlay? This clears the current picks and actual ticket odds so everyone can build a new ticket.'))return;
   S.busy=true;try{await api('reset',{year:S.data.year,week:S.week},true);S.tab='picks';S.manage=false;S.draft=null;S.editing=false;say('Parlay reset. A new ticket is open.');await refresh();}catch(err){say(err.message,true);await refresh();}finally{S.busy=false;render();}
  }
  if(act==='refresh'||act==='retry'){if(S.configError||!S.config){S.config=null;await window.LeagueParlay.paint(S.host,S.cr);return;}await restore();await refresh(true);}
  if(act==='history'){S.week=Number(b.dataset.week);S.tab='ticket';render();}
  if(act==='prop'){await save({gameId:document.getElementById('pn-prop-game').value,market:'prop',description:document.getElementById('pn-prop').value,odds:document.getElementById('pn-prop-odds').value});}
  if(act==='placed-odds'||act==='clear-placed-odds'){
   if(!admin()||S.pending)return;const request={year:S.data.year,week:S.week,revision:week().ticketOddsRevision||0,...(act==='clear-placed-odds'?{clear:true}:{odds:S.host.querySelector('#pn-placed-odds').value})};S.busy=true;
   try{await api('placed-odds',request,true);say(request.clear?'Actual odds cleared.':'Actual ticket odds saved.');await refresh();}catch(err){say(err.message,true);if(err.status===409)await refresh();}finally{S.busy=false;render();}
  }
  if(act==='review'){try{await api('review',{year:S.data.year,week:S.week,member:b.dataset.member,result:S.host.querySelector(`[data-review="${b.dataset.member}"]`).value,note:S.host.querySelector(`[data-note="${b.dataset.member}"]`).value},true);say('Result saved.');await refresh();}catch(e){say(e.message,true);render();}}
 });
 document.addEventListener('change',async e=>{if(!owns()||S.busy)return;if(e.target.id==='pn-demo'&&e.target.value){try{await api('demo',{stage:e.target.value});S.draft=null;S.editing=false;await refresh();}catch(err){say(err.message,true);}render();return;}if(e.target.id==='pn-week'){S.week=Number(e.target.value);S.draft=null;S.editing=false;render();}if(e.target.id==='pn-target'){S.target=e.target.value;S.draft=null;S.editing=false;render();}});
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&owns()&&S.config?.enabled)refresh();});
 setInterval(()=>{if(owns()&&S.config?.enabled&&document.visibilityState!=='hidden'&&!S.busy&&!S.host.querySelector('details.pn-review[open],details[data-detail="prop"][open],details[data-detail="placed-odds"][open]'))refresh();},20000);
 window.LeagueParlay={...legacy,take(payload){
  const result=legacy.take(payload);try{const raw=atob(String(payload).replace(/-/g,'+').replace(/_/g,'/'));const pick=JSON.parse(new TextDecoder().decode(Uint8Array.from(raw,c=>c.charCodeAt(0))));if(['ok','dupe'].includes(result))sharedPick=pick;}catch{}return result;
 },async paint(host,cr,apiContext){
  const id=++paintId;S.host=host;S.cr=cr;host.dataset.parlayMode='next';S.checking=true;
  // Replace the previous view synchronously, before the first network await.
  if(S.data)render();else host.innerHTML='<div class="pn"><p class="pn-note" role="status">Loading the shared parlay…</p></div>';
  let c;try{c=await config();}catch(e){S.checking=false;say(e.message,true);render();return;}
  if(id!==paintId||host.dataset.view!=='parlay')return;
  if(!c.enabled){host.dataset.parlayMode='legacy';return legacy.paint(host,cr,apiContext);}
  const cached=read(CACHE);if(!S.data&&cached?.api===c.api&&cached.data?.year===c.year){S.data=cached.data;S.week=S.data.current;S.pending=true;}render();await restore();await refresh();
 }};
})();
