const assert = require('node:assert/strict');
const {capture, facts, rowsHTML, highlights} = require('./rankings-view.js');
const clone = x => JSON.parse(JSON.stringify(x));
const week = (k, y=2026) => ({v:1,y,k,r:1,l:'After Week '+k,d:y+'-09-16',b:'Do not display this author',o:Array.from({length:12},(_,i)=>['Team '+i,i<6?'1-0':'0-1',160-i*5,'Original write-up '+i,i+1,null,'Manager '+i,'M'+i])});
const first = week(1), data = facts(first);
assert.equal(data.avg,132.5);
assert.equal(data.rows[0].scoringRank,1);
assert.equal(data.rows[11].scoringRank,12);
assert.deepEqual(data.rows[0].allPlay,[11,0,0]);
assert.deepEqual(data.rows[11].allPlay,[0,11,0]);
assert.equal(data.rows[0].lastScore,160);
assert.equal(data.rows[0].movement,null);
assert.deepEqual(data.rows[0].form,[{week:1,result:'W'}]);
assert.deepEqual(data.rows[11].form,[{week:1,result:'L'}]);
assert.equal(data.closest.gap,5);
assert.match(highlights(data),/First edition/);
const tied = clone(first); tied.o[1][2]=160;
const tiedData=facts(tied);
assert.equal(tiedData.rows[1].scoringRank,1);
assert.equal(tiedData.rows[0].tied,true);
assert.equal(tiedData.rows[0].allPlay,null,'rounded-score ties cannot prove exact all-play ties');
assert.match(highlights(tiedData),/2 teams tied/);
const second=week(2); second.o.unshift(second.o.pop());
second.o[0][0]='Renamed team'; second.o.forEach(r=>r[1]='1-1');
const older=week(9,2025), future=week(3);
const secondData=facts(second,[first,older,future]);
assert.equal(secondData.rows[0].movement,11,'movement follows stable manager identity');
assert.deepEqual(secondData.rows[0].trail,[{week:1,rank:12},{week:2,rank:1}]);
assert.deepEqual(secondData.rows[0].form,[{week:1,result:'L'},{week:2,result:'W'}]);
assert.equal(secondData.rows[0].allPlay,null,'later all-play is never inferred from cumulative PPG');
assert.equal(secondData.rows[0].lastScore,null,'PPG is not a weekly score after Week 1');
assert.match(highlights(secondData),/Scoring leader/);
const gap=facts(week(4),[first]);
assert.equal(gap.rows[0].form[2].result,null);
const html=rowsHTML(gap,{crest:()=>'',me:'M1'});
assert(!html.includes('class="rk-trend"'),'a missing week must break the line');
assert.match(html,/vs Week 1/);
assert(!html.includes(first.b));
assert.match(html,/The write-up/);
assert.match(html,/lg-mine/);
assert.equal((html.match(/data-rank-detail=/g)||[]).length,12);
const unsafe=week(1); unsafe.o[0][3]='<img src=x onerror=alert(1)>';
assert(rowsHTML(facts(unsafe),{crest:()=>'',me:null}).includes('&lt;img'));
const preseason=week(0); preseason.r=0; preseason.o.forEach(r=>{r[1]='0-0';r[2]=null});
assert.equal(facts(preseason).avg,null);
assert.equal(facts(preseason).rows[0].scoringRank,null);
assert.match(highlights(facts(preseason)),/No games yet/);
// Exact full-precision scores, a real zero and ties survive publication.
const season={teams:Array.from({length:12},(_,i)=>({teamId:i,scores:[i===0?0:100+i,150,0],outcomes:['L','W','']}))};
const captured=capture(season,0,2);
assert.deepEqual(captured.scores,[0,150]);
assert.deepEqual(captured.outcomes,['L','W']);
assert.deepEqual(captured.allPlay,[0,11,11]);
assert.equal(capture(season,0,0),null);
const noOutcomes=clone(season);noOutcomes.teams.forEach(t=>delete t.outcomes);
const noResult=capture(noOutcomes,1,2);
assert(!Object.hasOwn(noResult,'outcomes'));
assert(!Object.hasOwn(noResult,'allPlay'),'missing played data never becomes a loss');
assert(!JSON.stringify(noResult).includes('null'),'Firebase cannot drop null keys from new payloads');
const enriched=week(2);enriched.o[0][8]=captured;
assert.deepEqual(facts(enriched).rows[0].allPlay,[0,11,11]);
assert.equal(facts(enriched).rows[0].lastScore,150);
assert.deepEqual(first,week(1),'rendering must never change the saved snapshot');
console.log('PASS: snapshot scoring, ties, weekly highlights, identity, season isolation, missing weeks, form, first-week states, escaping and publication capture.');
